name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator@4.0.0

      - name: Download unobfuscated worker script
        run: |
          echo "⬇️ Downloading BPB worker script..."
          wget -q --retry-connrefused --tries=3 -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js

      - name: Verify downloaded file
        run: |
          if [ ! -f origin.js ]; then
            echo "❌ Failed to download origin.js"
            exit 1
          fi

      - name: Obfuscate BPB worker js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 0.3 \
          --dead-code-injection false \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding base64 \
          --string-array-threshold 0.5 \
          --transform-object-keys false \
          --unicode-escape-sequence false

      - name: Check for changes
        id: check-changes
        run: echo "changes_exist=$(git status --porcelain | wc -l | xargs)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: ${{ steps.check-changes.outputs.changes_exist > 0 }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
